### ISSUE TITLE
Hotkey Manager

### ISSUE THREAD

**Issue by eried** [Willy-Kimura/HotkeyListener#1]
Hi!

I am looking for a way to do a hotkey editor like the one in Visual Studio for example, a list with hotkeys and you could assign 1 hotkey per row. Can I easily serialize all hotkeys with your library? In a first stage, it would be just select which action-> change hotkey and a small modal window will pop to capture your new hotkey and reassign it

**Comment by Willy-Kimura** [comment]
That's very possible!

I considered such use-cases from the very beginning in case there is need for developing third-party hotkey management applications.

**Comment by eried** [comment]
Nice! But it would work already for 2 simple operations I need: 1) serialize from "settings" 2) compare "pressed" key to a hotkey? (including the modifiers?) or I have to hack my way around? I was just checking the list in nuget to find the most suitable

**Comment by Willy-Kimura** [comment]
Well, on those two:

1. Yes, you can easily serialize hotkeys as settings using the `Hotkey` class for all your saved hotkeys.
2. If you're talking about listening to keys, then that's a bit different since that's a **keyboard listener**. A hotkey listener **only** listens for the registered hotkeys and not all keys. You can try checking out [this library](https://github.com/johnkoerner/KeyboardListener) and probably integrate it with HotkeyListener in your app. And yes, this too is achievable.

I could try helping you out once I find time, but you may proceed and see how far it goes...
Feel free to reach out if stuck.
